# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poat',
            new_name='Post',
        ),
    ]
