# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 14:11
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20161129_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=redactor.fields.RedactorField(max_length=10000, verbose_name='Контент'),
        ),
    ]
